name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 

      - name: Build binaries
        run: |
          export CGO_ENABLED=0
          make build VERSION=${{ steps.get_version.outputs.version-without-v }}

      - name: Archive artifacts
        run: |
          cd dist
          for dir in */ ; do
            dir_name="${dir%/}"
            mv "$dir_name" "gcode"
            tar -cvzf "gcode-${{ steps.get_version.outputs.version }}-${dir_name}.tar.gz" "gcode"
            rm -r gcode
          done
          ls -l
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*

      - name: Update Version
        run: |
          git fetch origin
          git checkout -b main origin/main
          echo "${{ steps.get_version.outputs.version-without-v }}" > VERSION

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .  # 添加所有更改的文件
          git commit -m '${{ steps.get_version.outputs.version }}' || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main